export const mockStopData = {
  stops: [
    {
      stop_id: 56829,
      latitude: 44.770138,
      longitude: -93.287037,
      description: "I-35W & Burnsville Pkwy Station",
    },
  ],
  alerts: [
    {
      stop_closed: false,
      alert_text:
        "Effective Saturday, June 17, service changes begin on the METRO Orange Line",
    },
  ],
  departures: [
    {
      actual: true,
      trip_id: "23358439-MAR23-MVS-BUS-Weekday-05",
      stop_id: 56829,
      departure_text: "18 Min",
      departure_time: 1686788765,
      description: "Minneapolis / Rapid",
      route_id: "904",
      route_short_name: "Orange",
      direction_id: 0,
      direction_text: "NB",
      schedule_relationship: "Scheduled",
    },
    {
      actual: false,
      trip_id: "23358440-MAR23-MVS-BUS-Weekday-05",
      stop_id: 56829,
      departure_text: "7:56",
      departure_time: 1686790560,
      description: "Minneapolis / Rapid",
      route_id: "904",
      route_short_name: "Orange",
      direction_id: 0,
      direction_text: "NB",
      schedule_relationship: "Scheduled",
    },
    {
      actual: false,
      trip_id: "23358441-MAR23-MVS-BUS-Weekday-05",
      stop_id: 56829,
      departure_text: "8:26",
      departure_time: 1686792360,
      description: "Minneapolis / Rapid",
      route_id: "904",
      route_short_name: "Orange",
      direction_id: 0,
      direction_text: "NB",
      schedule_relationship: "Scheduled",
    },
    {
      actual: false,
      trip_id: "23358442-MAR23-MVS-BUS-Weekday-05",
      stop_id: 56829,
      departure_text: "8:56",
      departure_time: 1686794160,
      description: "Minneapolis / Rapid",
      route_id: "904",
      route_short_name: "Orange",
      direction_id: 0,
      direction_text: "NB",
      schedule_relationship: "Scheduled",
    },
  ],
};
